
title: Removing Distortion in Music Using Deep Neural Networks
email: johannes.imort@rwth-aachen.de
description: Johannes Imort, Giorgio Fabbro, Marco A. Martínez Ramírez, Stefan Uhlich, Yuichiro Koyama, and Yuki Mitsufuji

theme: jekyll-theme-cayman
github:
  is_project_page: false

# remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
